# general settings
name: 004_MDBN_x4_carbonate2D-x4_epoch4_NEW
model_type: SRModel
scale: 4
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: carbonate2D
    type: PairedImageDataset
    dataroot_gt: ./datasets/DeepRockSR_train/carbonate2D/carbonate2D_train_HR
    dataroot_lq: ./datasets/DeepRockSR_train/carbonate2D/carbonate2D_train_LR_default_X4
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: "{}"
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # val:
  #   name: carbonateD
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/Set5/GTmod12
  #   dataroot_lq: datasets/Set5/LRbicx2
  #   io_backend:
  #     type: disk

  val:
    name: carbonate2D
    type: PairedImageDataset
    dataroot_gt: ./datasets/DeepRockSR_test/carbonate2D/carbonate2D_test_HR
    dataroot_lq: ./datasets/DeepRockSR_test/carbonate2D/carbonate2D_test_LR_default_X4
    io_backend:
      type: disk

# network structures
network_g:
  type: SMANet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 12
  upscale: 4
  res_scale: 1.0

# path
path:
  pretrain_network_g: 
  param_key_g: params_ema
  strict_load_g: true
  resume_state: 

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [80000]
    restart_weights: [1]
    eta_min: !!float 1e-7
  #  scheduler:
  #    type: MultiStepLR
  #    milestones: [200000]
  #    gamma: 0.9

  total_iter: 80000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 800
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2 # 2/3/4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2 # 2/3/4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1600
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
